export const githubData = [
  {
    login: 'Sput',
    id: 1197741,
    node_id: 'MDQ6VXNlcjExOTc3NDE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1197741?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Sput',
    html_url: 'https://github.com/Sput',
    followers_url: 'https://api.github.com/users/Sput/followers',
    following_url: 'https://api.github.com/users/Sput/following{/other_user}',
    gists_url: 'https://api.github.com/users/Sput/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Sput/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Sput/subscriptions',
    organizations_url: 'https://api.github.com/users/Sput/orgs',
    repos_url: 'https://api.github.com/users/Sput/repos',
    events_url: 'https://api.github.com/users/Sput/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Sput/received_events',
    type: 'User',
    site_admin: false,
  },
  {
  "login": "Eddyfu45",
  "id": 80065083,
  "node_id": "MDQ6VXNlcjgwMDY1MDgz",
  "avatar_url": "https://avatars.githubusercontent.com/u/80065083?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Eddyfu45",
  "html_url": "https://github.com/Eddyfu45",
  "followers_url": "https://api.github.com/users/Eddyfu45/followers",
  "following_url": "https://api.github.com/users/Eddyfu45/following{/other_user}",
  "gists_url": "https://api.github.com/users/Eddyfu45/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Eddyfu45/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Eddyfu45/subscriptions",
  "organizations_url": "https://api.github.com/users/Eddyfu45/orgs",
  "repos_url": "https://api.github.com/users/Eddyfu45/repos",
  "events_url": "https://api.github.com/users/Eddyfu45/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Eddyfu45/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Edison",
  "company": null,
  "blog": "",
  "location": "New York",
  "email": null,
  "hireable": null,
  "bio": "Software Engineer",
  "twitter_username": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 1,
  "following": 0,
  "created_at": "2021-03-04T18:47:34Z",
  "updated_at": "2021-05-24T05:20:19Z"
  },
  {
    login: 'romebell',
    id: 13144457,
    node_id: 'MDQ6VXNlcjEzMTQ0NDU3',
    avatar_url: 'https://avatars.githubusercontent.com/u/13144457?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/romebell',
    html_url: 'https://github.com/romebell',
    followers_url: 'https://api.github.com/users/romebell/followers',
    following_url:
      'https://api.github.com/users/romebell/following{/other_user}',
    gists_url: 'https://api.github.com/users/romebell/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/romebell/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/romebell/subscriptions',
    organizations_url: 'https://api.github.com/users/romebell/orgs',
    repos_url: 'https://api.github.com/users/romebell/repos',
    events_url: 'https://api.github.com/users/romebell/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/romebell/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jshawndunn',
    id: 20318945,
    node_id: 'MDQ6VXNlcjIwMzE4OTQ1',
    avatar_url: 'https://avatars.githubusercontent.com/u/20318945?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jshawndunn',
    html_url: 'https://github.com/jshawndunn',
    followers_url: 'https://api.github.com/users/jshawndunn/followers',
    following_url:
      'https://api.github.com/users/jshawndunn/following{/other_user}',
    gists_url: 'https://api.github.com/users/jshawndunn/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jshawndunn/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jshawndunn/subscriptions',
    organizations_url: 'https://api.github.com/users/jshawndunn/orgs',
    repos_url: 'https://api.github.com/users/jshawndunn/repos',
    events_url: 'https://api.github.com/users/jshawndunn/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jshawndunn/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'omunoz-89',
    id: 49264189,
    node_id: 'MDQ6VXNlcjQ5MjY0MTg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/49264189?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/omunoz-89',
    html_url: 'https://github.com/omunoz-89',
    followers_url: 'https://api.github.com/users/omunoz-89/followers',
    following_url:
      'https://api.github.com/users/omunoz-89/following{/other_user}',
    gists_url: 'https://api.github.com/users/omunoz-89/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/omunoz-89/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/omunoz-89/subscriptions',
    organizations_url: 'https://api.github.com/users/omunoz-89/orgs',
    repos_url: 'https://api.github.com/users/omunoz-89/repos',
    events_url: 'https://api.github.com/users/omunoz-89/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/omunoz-89/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'charlenebatiste',
    id: 67442041,
    node_id: 'MDQ6VXNlcjY3NDQyMDQx',
    avatar_url: 'https://avatars.githubusercontent.com/u/67442041?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/charlenebatiste',
    html_url: 'https://github.com/charlenebatiste',
    followers_url: 'https://api.github.com/users/charlenebatiste/followers',
    following_url:
      'https://api.github.com/users/charlenebatiste/following{/other_user}',
    gists_url: 'https://api.github.com/users/charlenebatiste/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/charlenebatiste/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/charlenebatiste/subscriptions',
    organizations_url: 'https://api.github.com/users/charlenebatiste/orgs',
    repos_url: 'https://api.github.com/users/charlenebatiste/repos',
    events_url: 'https://api.github.com/users/charlenebatiste/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/charlenebatiste/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'brandonhall96',
    id: 73011352,
    node_id: 'MDQ6VXNlcjczMDExMzUy',
    avatar_url: 'https://avatars.githubusercontent.com/u/73011352?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/brandonhall96',
    html_url: 'https://github.com/brandonhall96',
    followers_url: 'https://api.github.com/users/brandonhall96/followers',
    following_url:
      'https://api.github.com/users/brandonhall96/following{/other_user}',
    gists_url: 'https://api.github.com/users/brandonhall96/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/brandonhall96/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/brandonhall96/subscriptions',
    organizations_url: 'https://api.github.com/users/brandonhall96/orgs',
    repos_url: 'https://api.github.com/users/brandonhall96/repos',
    events_url: 'https://api.github.com/users/brandonhall96/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/brandonhall96/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'aprin418',
    id: 77419893,
    node_id: 'MDQ6VXNlcjc3NDE5ODkz',
    avatar_url: 'https://avatars.githubusercontent.com/u/77419893?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/aprin418',
    html_url: 'https://github.com/aprin418',
    followers_url: 'https://api.github.com/users/aprin418/followers',
    following_url:
      'https://api.github.com/users/aprin418/following{/other_user}',
    gists_url: 'https://api.github.com/users/aprin418/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/aprin418/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/aprin418/subscriptions',
    organizations_url: 'https://api.github.com/users/aprin418/orgs',
    repos_url: 'https://api.github.com/users/aprin418/repos',
    events_url: 'https://api.github.com/users/aprin418/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/aprin418/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'evan-woodworth',
    id: 80374875,
    node_id: 'MDQ6VXNlcjgwMzc0ODc1',
    avatar_url: 'https://avatars.githubusercontent.com/u/80374875?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/evan-woodworth',
    html_url: 'https://github.com/evan-woodworth',
    followers_url: 'https://api.github.com/users/evan-woodworth/followers',
    following_url:
      'https://api.github.com/users/evan-woodworth/following{/other_user}',
    gists_url: 'https://api.github.com/users/evan-woodworth/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/evan-woodworth/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/evan-woodworth/subscriptions',
    organizations_url: 'https://api.github.com/users/evan-woodworth/orgs',
    repos_url: 'https://api.github.com/users/evan-woodworth/repos',
    events_url: 'https://api.github.com/users/evan-woodworth/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/evan-woodworth/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'anthonymang',
    id: 80987583,
    node_id: 'MDQ6VXNlcjgwOTg3NTgz',
    avatar_url: 'https://avatars.githubusercontent.com/u/80987583?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/anthonymang',
    html_url: 'https://github.com/anthonymang',
    followers_url: 'https://api.github.com/users/anthonymang/followers',
    following_url:
      'https://api.github.com/users/anthonymang/following{/other_user}',
    gists_url: 'https://api.github.com/users/anthonymang/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/anthonymang/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/anthonymang/subscriptions',
    organizations_url: 'https://api.github.com/users/anthonymang/orgs',
    repos_url: 'https://api.github.com/users/anthonymang/repos',
    events_url: 'https://api.github.com/users/anthonymang/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/anthonymang/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'amanda-posey',
    id: 81441909,
    node_id: 'MDQ6VXNlcjgxNDQxOTA5',
    avatar_url: 'https://avatars.githubusercontent.com/u/81441909?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/amanda-posey',
    html_url: 'https://github.com/amanda-posey',
    followers_url: 'https://api.github.com/users/amanda-posey/followers',
    following_url:
      'https://api.github.com/users/amanda-posey/following{/other_user}',
    gists_url: 'https://api.github.com/users/amanda-posey/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/amanda-posey/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/amanda-posey/subscriptions',
    organizations_url: 'https://api.github.com/users/amanda-posey/orgs',
    repos_url: 'https://api.github.com/users/amanda-posey/repos',
    events_url: 'https://api.github.com/users/amanda-posey/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/amanda-posey/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'behemoth0132',
    id: 81875454,
    node_id: 'MDQ6VXNlcjgxODc1NDU0',
    avatar_url: 'https://avatars.githubusercontent.com/u/81875454?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/behemoth0132',
    html_url: 'https://github.com/behemoth0132',
    followers_url: 'https://api.github.com/users/behemoth0132/followers',
    following_url:
      'https://api.github.com/users/behemoth0132/following{/other_user}',
    gists_url: 'https://api.github.com/users/behemoth0132/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/behemoth0132/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/behemoth0132/subscriptions',
    organizations_url: 'https://api.github.com/users/behemoth0132/orgs',
    repos_url: 'https://api.github.com/users/behemoth0132/repos',
    events_url: 'https://api.github.com/users/behemoth0132/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/behemoth0132/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jakeschultz89',
    id: 81945834,
    node_id: 'MDQ6VXNlcjgxOTQ1ODM0',
    avatar_url: 'https://avatars.githubusercontent.com/u/81945834?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jakeschultz89',
    html_url: 'https://github.com/jakeschultz89',
    followers_url: 'https://api.github.com/users/jakeschultz89/followers',
    following_url:
      'https://api.github.com/users/jakeschultz89/following{/other_user}',
    gists_url: 'https://api.github.com/users/jakeschultz89/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jakeschultz89/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/jakeschultz89/subscriptions',
    organizations_url: 'https://api.github.com/users/jakeschultz89/orgs',
    repos_url: 'https://api.github.com/users/jakeschultz89/repos',
    events_url: 'https://api.github.com/users/jakeschultz89/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jakeschultz89/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'noncenze',
    id: 82400098,
    node_id: 'MDQ6VXNlcjgyNDAwMDk4',
    avatar_url: 'https://avatars.githubusercontent.com/u/82400098?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/noncenze',
    html_url: 'https://github.com/noncenze',
    followers_url: 'https://api.github.com/users/noncenze/followers',
    following_url:
      'https://api.github.com/users/noncenze/following{/other_user}',
    gists_url: 'https://api.github.com/users/noncenze/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/noncenze/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/noncenze/subscriptions',
    organizations_url: 'https://api.github.com/users/noncenze/orgs',
    repos_url: 'https://api.github.com/users/noncenze/repos',
    events_url: 'https://api.github.com/users/noncenze/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/noncenze/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'mauricechevez',
    id: 82402602,
    node_id: 'MDQ6VXNlcjgyNDAyNjAy',
    avatar_url: 'https://avatars.githubusercontent.com/u/82402602?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mauricechevez',
    html_url: 'https://github.com/mauricechevez',
    followers_url: 'https://api.github.com/users/mauricechevez/followers',
    following_url:
      'https://api.github.com/users/mauricechevez/following{/other_user}',
    gists_url: 'https://api.github.com/users/mauricechevez/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/mauricechevez/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/mauricechevez/subscriptions',
    organizations_url: 'https://api.github.com/users/mauricechevez/orgs',
    repos_url: 'https://api.github.com/users/mauricechevez/repos',
    events_url: 'https://api.github.com/users/mauricechevez/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/mauricechevez/received_events',
    type: 'User',
    site_admin: false,
  },
]
